In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Top_Stocks = pd.read_csv('C:/Users/User/Project 3/Final_Cannabis_Financial_Data.csv')
Top_Stocks

,Unnamed: 0,EPS,Ticker,Quarter-Year,CFPS,PE_Ratio,Market_Cap,ROE,Price_Sales_Ratio,Payout_Ratio,Debt_Equity_Ratio,Quarter,Final_Rating
0,0,-2.382436,AMRS,2019,-0.428783,-3.414150,2.686322e+08,0.307620,6.627003,0.000000,-1.629322,4.0,0
1,1,-2.382436,AMRS,2019,-0.604417,-5.340485,3.123970e+08,0.273325,8.937630,0.000000,-1.598623,3.0,0
2,2,-2.382436,AMRS,2019,-0.250816,-6.592642,2.511006e+08,0.210116,4.005177,0.000000,-1.677527,2.0,0
3,3,-2.382436,AMRS,2019,-0.477087,-5.242124,3.472540e+08,0.278172,24.158482,0.000000,-1.441540,1.0,0
4,4,-2.224219,AMRS,2018,-0.663896,1.162761,1.006311e+08,-0.397440,1.221459,0.000000,-1.587469,4.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,401,-8.500000,CRON,2020,-0.133061,27.248498,2.071976e+09,0.044301,245.727678,0.000000,0.123201,1.0,0
398,402,-8.500000,GWPH,2020,-0.067170,-4671.691299,3.721002e+10,-0.011140,308.456402,0.000000,0.050209,1.0,0
399,403,-8.500000,SMG,2020,-5.321364,28.395515,7.161349e+09,0.319362,5.178875,0.130849,4.237052,1.0,0
400,404,-8.500000,TAP,2020,-0.083333,-77.027478,8.858160e+09,-0.009065,4.214158,-1.069565,1.223002,1.0,0
401,405,-8.500000,MO,2020,1.656082,46.988724,7.292650e+10,0.237200,11.468234,1.007088,7.041877,1.0,0

In [3]:
Top_Stocks_2 = Top_Stocks.groupby(["Ticker","Quarter-Year"],as_index=False)["Market_Cap"].mean()

In [4]:
Top_Stocks_2

    Ticker  Quarter-Year    Market_Cap
0     AMRS          2010  3.798402e+09
1     AMRS          2011  1.323073e+10
2     AMRS          2012  2.498001e+09
3     AMRS          2013  3.504114e+09
4     AMRS          2014  3.532717e+09
..     ...           ...           ...
131   TRST          2020  6.077674e+08
132   YCBD          2017  3.352257e+07
133   YCBD          2018  3.409912e+07
134   YCBD          2019  5.555733e+07
135   YCBD          2020  3.504288e+10

[136 rows x 3 columns]

In [5]:
Top_Stocks_3 = Top_Stocks_2.groupby(["Ticker"],as_index=False)["Market_Cap"].mean()
Top_Stocks_3

   Ticker    Market_Cap
0    AMRS  3.024180e+09
1     BUD           NaN
2    CARA  4.675849e+08
3     CGC  5.568611e+09
4    CRBP  6.432034e+10
5    CRON  2.189438e+09
6    GWPH  3.977937e+10
7    IIPR  6.206556e+08
8      MO  9.500501e+10
9    NBEV  6.206848e+09
10    SMG  3.702029e+09
11    TAP  8.899637e+09
12   TLRY  3.195093e+09
13   TRST  6.248590e+08
14   YCBD  8.791516e+09

In [6]:
Top_Stocks_4 = Top_Stocks_3.sort_values(by='Market_Cap',ascending=False).reset_index()

In [7]:
Top_Stocks_5 = Top_Stocks_4.head(10)
Top_Stocks_5

   index Ticker    Market_Cap
0      8     MO  9.500501e+10
1      4   CRBP  6.432034e+10
2      6   GWPH  3.977937e+10
3     11    TAP  8.899637e+09
4     14   YCBD  8.791516e+09
5      9   NBEV  6.206848e+09
6      3    CGC  5.568611e+09
7     10    SMG  3.702029e+09
8     12   TLRY  3.195093e+09
9      0   AMRS  3.024180e+09

In [10]:
Top_Stocks_5.to_csv('C:/Users/User/Project 3/TOP10_Stocks.csv')